/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Tubes_Kel6.Kurir;
import Tubes_Kel6.Transaksi;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paman
 */
public class ConfirmStatus extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmStatus
     */
    public ConfirmStatus() {
        initComponents();
        tracking_cbUbahStatus.setVisible(false);
        tracking_btnSubmit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tracking_btnCari = new javax.swing.JButton();
        tracking_idTransaksi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tracking_btnSubmit = new javax.swing.JButton();
        tracking_cbUbahStatus = new javax.swing.JComboBox<>();
        tracking_btnUbahStatus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tracking_tblTracking = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnback = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Konfirmasi Status");
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tracking_btnCari.setText("Cari");
        tracking_btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracking_btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(tracking_btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        tracking_idTransaksi.setBackground(new java.awt.Color(240, 240, 240));
        tracking_idTransaksi.setBorder(null);
        tracking_idTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracking_idTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(tracking_idTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 120, -1));

        jLabel14.setText("ID Transaksi :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 111, -1, -1));

        tracking_btnSubmit.setText("Submit");
        tracking_btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracking_btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(tracking_btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, -1, -1));

        tracking_cbUbahStatus.setEditable(true);
        tracking_cbUbahStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diproses", "Dikemas", "Dikirim", "Sampai kota tujuan", "Diterima" }));
        getContentPane().add(tracking_cbUbahStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 222, -1));

        tracking_btnUbahStatus.setText("Ubah Status");
        tracking_btnUbahStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracking_btnUbahStatusActionPerformed(evt);
            }
        });
        getContentPane().add(tracking_btnUbahStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        tracking_tblTracking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "Pengirim", "Penerima", "Alamat Tujuan", "Jenis Pengiriman", "Total Harga", "Pembayaran", "Tanggal Transaksi", "Status Barang"
            }
        ));
        tracking_tblTracking.setGridColor(new java.awt.Color(240, 240, 240));
        tracking_tblTracking.setSelectionBackground(new java.awt.Color(66, 58, 97));
        tracking_tblTracking.setSelectionForeground(new java.awt.Color(244, 244, 246));
        jScrollPane2.setViewportView(tracking_tblTracking);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 917, 115));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 58, 97));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Konfirmasi Status");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 230, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 58, 97), 2));
        jPanel2.setOpaque(false);

        btnback.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(66, 58, 97));
        btnback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnback.setText("< Back");
        btnback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(btnback, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnback, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 120, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 940, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tracking_btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracking_btnSubmitActionPerformed
        String id = tracking_tblTracking.getValueAt(tracking_tblTracking.getSelectedRow(), 0).toString();
        String status = tracking_cbUbahStatus.getSelectedItem().toString();
        //System.out.println("GUI.User.tracking_btnSubmitActionPerformed() id="+id);
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih transaksi terlebih dahulu", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                new Kurir().updateStatus(id, status);
                JOptionPane.showMessageDialog(null, "Update sukses ", "Sukses", JOptionPane.INFORMATION_MESSAGE);

                DefaultTableModel model = (DefaultTableModel) tracking_tblTracking.getModel();
                model.setRowCount(0);
                viewTrackingTransaksi(id);

                tracking_cbUbahStatus.setVisible(false);
                tracking_btnSubmit.setVisible(false);
            } catch (Exception e) {
                System.out.println("GUI.User.tracking_btnSubmitActionPerformed()" + e);
            }
        }
    }//GEN-LAST:event_tracking_btnSubmitActionPerformed

    private void tracking_btnUbahStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracking_btnUbahStatusActionPerformed
        tracking_cbUbahStatus.setVisible(true);
        tracking_btnSubmit.setVisible(true);
    }//GEN-LAST:event_tracking_btnUbahStatusActionPerformed

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new HomeKurir().setVisible(true);
    }//GEN-LAST:event_btnbackMouseClicked

    private void tracking_btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracking_btnCariActionPerformed
        String id = tracking_idTransaksi.getText();
        DefaultTableModel model = (DefaultTableModel) tracking_tblTracking.getModel();
        model.setRowCount(0);
        viewTrackingTransaksi(id);
    }//GEN-LAST:event_tracking_btnCariActionPerformed

    private void tracking_idTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracking_idTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tracking_idTransaksiActionPerformed
    
    public void viewTrackingTransaksi(String id) {
        try {
            Kurir kurir = new Kurir();
            ArrayList<Transaksi> list = kurir.operator_tracking(id);
            DefaultTableModel model = (DefaultTableModel) tracking_tblTracking.getModel();
            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Object[] row = new Object[9];
                for (int i = 0; i < list.size(); i++) {
                    row[0] = list.get(i).getId_transaksi();
                    row[1] = list.get(i).getPengirim();
                    row[2] = list.get(i).getPenerima();
                    row[3] = list.get(i).getAlamat_tujuan();
                    row[4] = list.get(i).getJenis_pengiriman();
                    row[5] = list.get(i).getTotal_harga();
                    row[6] = list.get(i).getPembayaran();
                    row[7] = list.get(i).getTanggal_transaksi();
                    row[8] = list.get(i).getStatus_barang();
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
            System.out.println("GUI.User.view_transaksi() " + e.toString());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton tracking_btnCari;
    private javax.swing.JButton tracking_btnSubmit;
    private javax.swing.JButton tracking_btnUbahStatus;
    private javax.swing.JComboBox<String> tracking_cbUbahStatus;
    private javax.swing.JTextField tracking_idTransaksi;
    private javax.swing.JTable tracking_tblTracking;
    // End of variables declaration//GEN-END:variables
}
