/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import Tubes_Kel6.Barang;
import Tubes_Kel6.DetailTransaksi;
import Tubes_Kel6.Keranjang;
import Tubes_Kel6.Transaksi;
import Tubes_Kel6.server;
import java.rmi.Naming;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author paman
 */
public class MetodePembayaran extends javax.swing.JFrame {

    /**
     * Creates new form MetodePembayaran
     */ 
    public MetodePembayaran() {
        initComponents();
        viewKeranjang();
        sum();
//        view_transaksi();
//        tracking_cbUbahStatus.setVisible(false);
//        tracking_btnSubmit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pembayaran_penerima = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pembayaran_tblKeranjang = new javax.swing.JTable();
        pembayaran_pengirim = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        pembayaran_alamatTujuan = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        pembayaran_totalHarga = new javax.swing.JTextField();
        pembayaran_btnHapusTbl = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pembayaran_pembayaran = new javax.swing.JTextField();
        layananStandard = new javax.swing.JRadioButton();
        pembayaran_btnBayar = new javax.swing.JButton();
        layananOneDay = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setText("Penerima         :");

        jLabel15.setText("Pengirim          :");

        jLabel11.setText("Barang");

        pembayaran_tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Barang", "Nama Barang", "Ukuran Barang", "Berat Barang", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(pembayaran_tblKeranjang);

        pembayaran_alamatTujuan.setColumns(20);
        pembayaran_alamatTujuan.setRows(5);
        jScrollPane4.setViewportView(pembayaran_alamatTujuan);

        jLabel12.setText("Total Harga     :");

        pembayaran_totalHarga.setEditable(false);

        pembayaran_btnHapusTbl.setText("Hapus");
        pembayaran_btnHapusTbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaran_btnHapusTblActionPerformed(evt);
            }
        });

        jLabel13.setText("Pembayaran    : ");

        jLabel16.setText("Jenis Pengiriman:");

        buttonGroup2.add(layananStandard);
        layananStandard.setText("Standard");
        layananStandard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layananStandardActionPerformed(evt);
            }
        });

        pembayaran_btnBayar.setText("Bayar");
        pembayaran_btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaran_btnBayarActionPerformed(evt);
            }
        });

        buttonGroup2.add(layananOneDay);
        layananOneDay.setText("One Day");
        layananOneDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layananOneDayActionPerformed(evt);
            }
        });

        jLabel9.setText("Alamat Tujuan :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pembayaran_btnHapusTbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pembayaran_btnBayar)
                            .addComponent(pembayaran_pembayaran)
                            .addComponent(pembayaran_totalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(layananStandard)
                                .addGap(18, 18, 18)
                                .addComponent(layananOneDay))
                            .addComponent(pembayaran_pengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pembayaran_penerima, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(pembayaran_btnHapusTbl))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(pembayaran_pengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pembayaran_penerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(layananStandard)
                    .addComponent(layananOneDay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pembayaran_totalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pembayaran_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pembayaran_btnBayar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pembayaran_btnHapusTblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaran_btnHapusTblActionPerformed
        String id = pembayaran_tblKeranjang.getValueAt(pembayaran_tblKeranjang.getSelectedRow(), 0).toString();
        try {
            new server().dalete_keranjang(id);
            new server().dalete_barang(id);

            DefaultTableModel model = (DefaultTableModel) pembayaran_tblKeranjang.getModel();
            model.setRowCount(0);
            viewKeranjang();
            sum();

            JOptionPane.showMessageDialog(null, "Delete barang sukses", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pembayaran_btnHapusTblActionPerformed

    private void layananStandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layananStandardActionPerformed
        sum();
    }//GEN-LAST:event_layananStandardActionPerformed

    private void pembayaran_btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaran_btnBayarActionPerformed
        try {
            int countkeranjang = (int) pembayaran_tblKeranjang.getRowCount();
            String pengirim = pembayaran_pengirim.getText();
            String penerima = pembayaran_penerima.getText();
            String alamat = pembayaran_alamatTujuan.getText();
            String jenis_pengiriman = "";
            if (layananStandard.isSelected()) {
                jenis_pengiriman = "Standard";
            } else if (layananOneDay.isSelected()) {
                jenis_pengiriman = "One Day";
            }
            int total_harga = Integer.parseInt(pembayaran_totalHarga.getText());
            int Pembayaran = Integer.parseInt(pembayaran_pembayaran.getText());
            String status_barang = "Diproses";

            if (pengirim.isEmpty() || penerima.isEmpty() || alamat.isEmpty() || jenis_pengiriman.isEmpty() || Pembayaran == 0) {
                JOptionPane.showMessageDialog(null, "Harap isi semua data", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if (countkeranjang < 1) {
                JOptionPane.showMessageDialog(null, "Anda belum memiliki barang untuk dikirim", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if (Pembayaran < total_harga) {
                JOptionPane.showMessageDialog(null, "Uang yang anda miliki tidak mencukupi untuk melakukan transaksi", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {

                new server().input_transaksi(pengirim, penerima, alamat, jenis_pengiriman, total_harga, Pembayaran, status_barang);

                input_detail();

                new server().truncate_keranjang();

                DefaultTableModel model = (DefaultTableModel) pembayaran_tblKeranjang.getModel();
                model.setRowCount(0);
                viewKeranjang();
                sum();

                pembayaran_pengirim.setText("");
                pembayaran_penerima.setText("");
                pembayaran_alamatTujuan.setText("");
                pembayaran_pembayaran.setText("");

                JOptionPane.showMessageDialog(null, "Transaksi sukses", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pembayaran_btnBayarActionPerformed

    private void layananOneDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layananOneDayActionPerformed
        sum();
    }//GEN-LAST:event_layananOneDayActionPerformed
    
    public void viewKeranjang() {
        try {
            ArrayList<Keranjang> list = new server().dataKeranjang();
            DefaultTableModel model = (DefaultTableModel) pembayaran_tblKeranjang.getModel();
            Object[] row = new Object[5];
            for (int i = 0; i < list.size(); i++) {
                row[0] = list.get(i).getId_barang();
                row[1] = list.get(i).getNama_barang();
                row[2] = list.get(i).getJenis_barang();
                row[3] = list.get(i).getBerat() + " Kg";
                row[4] = "Rp. " + list.get(i).getSub_total();
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodePembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodePembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodePembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodePembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodePembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton layananOneDay;
    private javax.swing.JRadioButton layananStandard;
    private javax.swing.JTextArea pembayaran_alamatTujuan;
    private javax.swing.JButton pembayaran_btnBayar;
    private javax.swing.JButton pembayaran_btnHapusTbl;
    private javax.swing.JTextField pembayaran_pembayaran;
    private javax.swing.JTextField pembayaran_penerima;
    private javax.swing.JTextField pembayaran_pengirim;
    private javax.swing.JTable pembayaran_tblKeranjang;
    private javax.swing.JTextField pembayaran_totalHarga;
    // End of variables declaration//GEN-END:variables
    public void input_detail() {
        try {
            server Service = new server();
            ArrayList<Keranjang> list = Service.dataKeranjang();
            int last_id = Integer.parseInt(Service.lastInput_transaksi());
            Object[] row = new Object[5];
            for (int i = 0; i < list.size(); i++) {
                row[0] = list.get(i).getId_barang();
                row[1] = list.get(i).getNama_barang();
                row[2] = list.get(i).getJenis_barang();
                row[3] = list.get(i).getBerat();
                row[4] = list.get(i).getSub_total();
                int id_barang = Integer.parseInt(row[0].toString());
                String nama_barang = row[1].toString();
                String jenis_barang = row[2].toString();
                int berat = Integer.parseInt(row[3].toString());
                int sub_total = Integer.parseInt(row[4].toString());
                Service.input_detailTransaksi(last_id, id_barang, nama_barang, jenis_barang, berat, sub_total);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    

    public void sum() {
        try {
            server Service = new server();
            Integer total = Integer.parseInt(Service.sum_subTotal());
            //System.out.println("GUI.User.sum() = "+total);
            if (total == 0) {
                pembayaran_totalHarga.setText("0");
            } else {
                if (layananStandard.isSelected()) {
                    total = total + 15000;
                } else if (layananOneDay.isSelected()) {
                    total = total + 25000;
                }
                String totali = total.toString();
                pembayaran_totalHarga.setText(totali);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

}
